services:
  database:
    container_name: TeamObjectBackend
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres